---

- name: Install Android SDKs for applicable releases
  command: "{{ android_sdk_install_location }}/sdk-install.expect"
  become: yes
  become_user: "{{ android_sdk_user }}"
  # Skip linting here, because I need to implement something more sane for checking pre-installed SDKs
  tags:
    - skip_ansible_lint
